# Generated by Django 4.0.5 on 2022-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
