# Generated by Django 4.0.5 on 2022-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
